# This workflow will install Python dependencies, run tests and lint with a single version of Python
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-python

name: Python application

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

permissions:
  contents: read

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2  # Use v2 instead of v3 for better compatibility
    - name: Set up Python 3.10
      uses: actions/setup-python@v2  # Use v2 instead of v3 for better compatibility
      with:
        python-version: "3.10"
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install fastapi Pillow uvicorn
        if [ -f requirements.txt ]; then pip install -r requirements.txt; fi
    - name: Lint with FastAPI
      run: |
        # Lint the FastAPI application
        uvicorn your_app_module:app --host 0.0.0.0 --port 8000 --reload
